# Generated by Django 3.2.4 on 2021-06-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=225)),
                ('message_text', models.CharField(max_length=225)),
            ],
        ),
    ]
