# Generated by Django 3.2.4 on 2021-06-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instantMessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatapp',
            new_name='InstantMessage',
        ),
    ]
