# Generated by Django 3.2.4 on 2021-06-21 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instantMessages', '0002_rename_chatapp_instantmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantmessage',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
