# Generated by Django 3.2.4 on 2021-06-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instantMessages', '0003_instantmessage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantmessage',
            name='user_name',
        ),
    ]
